name: "My fibbot"
description: "A Rust program that prints Hello world and handles parameters"
inputs:
  enable_fib:
    description: "Enabling Fibonacci"
    required: true
    default: "false"
  max_threshold:
    description: "The maximum number of Fibonacci calculations"
    required: true
    default: "500"
outputs:
  enable_fib:
    description: "Captured enable_fib value"
  max_threshold:
    description: "Captured max_threshold value"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - "sh"
    - "-c"
    - |
      echo "Running Rust program..."
      /app/target/release/fibbot ${{ inputs.enable_fib }} ${{ inputs.max_threshold }}

      echo "Listing contents before moving output.txt..."
      ls -lah /

      echo "Moving output.txt to /github/workspace/..."
      mv /output.txt /github/workspace/output.txt || { echo "Failed to move output.txt"; exit 1; }

      echo "Final verification inside container:"
      ls -lah /github/workspace/
