name: "My fibbot"
description: "A Rust program that prints Hello world and handles parameters"
inputs:
  enable_fib:
    description: "Enabling Fibonacci"
    required: true
    default: "false"
  max_threshold:
    description: "The maximum number of Fibonacci calculations"
    required: true
    default: "500"
outputs:
  enable_fib:
    description: "Captured enable_fib value"
  max_threshold:
    description: "Captured max_threshold value"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - "${{ inputs.enable_fib }}"
    - "${{ inputs.max_threshold }}"
  entrypoint: "/bin/sh"
  args:
    - "-c"
    - "./fibbot | tee /github/workspace/output.txt"
