name: ci
on: [push, pull_request]
jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run Fibbot
        id: input-parse
        uses: ./
        with:
          enable_fib: false
          max_threshold: '10000'

      - name: display output
        run: echo "The inputs are ${{ steps.inputs.outputs.enable_fib }} and ${{ steps.inputs.outputs.max_threshold }}" 
