name: Run Rust Action
on: [push, pull_request]
jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Fibbot
        id: input-parse
        uses: ./
        with:
          enable_fib: "false"
          max_threshold: "1000"

      - name: display output
        run: echo "The inputs are ${{ steps.input-parse.outputs.enable_fib }} and ${{ steps.input-parse.outputs.max_threshold }}"
