name: Run Rust Action
on: [push, pull_request]
jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Fibbot
        id: fibbot
        uses: ./
        with:
          enable_fib: "false"
          max_threshold: "1000"

      - name: Read and set outputs
        run: |
          if [ -f "/github/workspace/output.txt" ]; then
            echo "enable_fib=$(sed -n '1p' /github/workspace/output.txt)" >> $GITHUB_ENV
            echo "max_threshold=$(sed -n '2p' /github/workspace/output.txt)" >> $GITHUB_ENV
          else
            echo "Error: output.txt not found!"
            exit 1
          fi

      - name: Display captured output
        run: echo "The inputs are ${{ env.enable_fib }} and ${{ env.max_threshold }}"
